# Generated by Django 3.2.16 on 2022-12-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('FUNDED', 'FUNDED'), ('OPEN', 'OPEN')], default='OPEN', max_length=50)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='investor.investor')),
            ],
        ),
    ]
