# Generated by Django 3.2.16 on 2022-12-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('FUNDED', 'FUNDED'), ('OPEN', 'OPEN')], default='OPEN', max_length=50),
        ),
    ]
