# Generated by Django 3.2.16 on 2022-12-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('loan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loan.loan')),
            ],
        ),
    ]
