# Generated by Django 3.2.16 on 2022-12-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20221223_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='installemnts',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
